spring.application.name=safetrade-backend


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Tell Hibernate to use the PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CRITICAL FOR TESTING: This automatically creates/updates your tables based on your Java Classes!
spring.jpa.hibernate.ddl-auto=update

# Optional: Show the SQL queries in your console so you can see what Spring is doing
# spring.jpa.show-sql=true
# database = safetrade_db_xm37
# username= safetrade_db_xm37_user
# password = 4lY6avqNfuREKp2q8wReigYFMXLTfdWL
#Url =jdbc:postgresql://dpg-d9f0csmrnols73f55n7g-a:5432/safetrade_db_xm37


# Paystack API configuration
paystack.secret.key=${PAYSTACK_SECRET_KEY:} 
# url=postgresql://safetrade_db_xm37_user:4lY6avqNfuREKp2q8wReigYFMXLTfdWL@dpg-d9f0csmrnols73f55n7g-a/safetrade_db_xm37
# Disable Spring Session (we are using JWT) - no need to set store-type since spring-session isn't included


# JWT signing secret (must be set as an environment variable, never hardcoded in production)
jwt.secret=${JWT_SECRET:your-super-secret-key-that-needs-to-be-at-least-256-bits-long!}