package com.safetrade.safetradebackend.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "trades")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Trades {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(nullable = false)
    private String title;

   @Column(unique = true)
   private String tradeCode;

   @Column(unique = true)
   private String riderCode;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(nullable = false)
    private Double price;

    @Column(nullable = true)
    private String buyerId;

    @Column(nullable = false)
    private String sellerId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TradeStatus status;

    private String riderId;

    @Column(columnDefinition = "TEXT")
    private String itemPhotoBase64;

    private String dispatchCode; // ST-XXXXXX generated by Seller
    private String dropOffCode;  // ST-XXXXXX generated by Rider
    private String releaseCode;  // ST-XXXXXX generated by Post Operator

    private LocalDateTime createdAt;
    private LocalDateTime riderPickedUpAt; // Used for 24-hour delivery SLA
    private LocalDateTime postArrivedAt;   // Used for 72-hour collection SLA
}
